# Generated by Django 4.0.4 on 2022-04-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='name')),
                ('surname', models.CharField(max_length=1000, verbose_name='surname')),
            ],
            options={
                'verbose_name': 'Workers',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
