# Generated by Django 4.0.4 on 2022-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listWorkers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees_Task_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('status', models.IntegerField(choices=[[1, 'task not complet'], [2, 'task completed']])),
                ('categories', models.CharField(max_length=1000, verbose_name='categories')),
                ('date_of_completion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Employees_Task_List',
                'verbose_name_plural': 'Employees_Task_List',
            },
        ),
    ]
