# Generated by Django 4.0.4 on 2022-05-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listWorkers', '0002_employees_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_task_list',
            name='idworker',
            field=models.CharField(default=1, max_length=10, verbose_name='idworker'),
            preserve_default=False,
        ),
    ]
