# Generated by Django 4.0.4 on 2022-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listWorkers', '0003_employees_task_list_idworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_task_list',
            name='status',
            field=models.CharField(max_length=1000, verbose_name='description'),
        ),
    ]
