# Generated by Django 4.0.4 on 2022-05-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listWorkers', '0004_alter_employees_task_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_task_list',
            name='status',
            field=models.CharField(max_length=100, verbose_name='status'),
        ),
    ]
