# Generated by Django 4.0.4 on 2022-05-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listWorkers', '0006_alter_employees_task_list_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_task_list',
            name='status',
            field=models.CharField(auto_created='Not complete', default=1, max_length=100, verbose_name='status'),
            preserve_default=False,
        ),
    ]
